---
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      max-parallel: 1
      matrix:
        # Available Python versions: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        python: [ '3.10', '3.11', '3.12', '3.13' ]
    name: python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: make ci
      - run: make test-examples || echo "Examples test exits with error"
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.STUDIO_GITHUB_TOKEN }}
          publish_dir: docs
